// Static file server for the Cortex client build.
// Serves pre-compressed .gz / .br files generated by vite-plugin-compression,
// with correct cache headers (long for hashed assets, no-cache for HTML).
import express from 'express';
import expressStaticGzip from 'express-static-gzip';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.join(__dirname, 'dist');
const PORT = process.env.PORT || 3000;

const app = express();

app.use(
  expressStaticGzip(DIST, {
    enableBrotli: true,
    orderPreference: ['br', 'gz'],
    serveStatic: {
      etag: true,
      lastModified: true,
      setHeaders(res, filePath) {
        if (filePath.endsWith('.html')) {
          // HTML must never be cached — it references hashed asset filenames
          res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
        } else {
          // Hashed assets (JS, CSS) are immutable — cache for 1 year
          res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
        }
      },
    },
  })
);

// SPA fallback: all unmatched routes serve index.html (Express 5 wildcard syntax)
app.get('/{*path}', (_req, res) => {
  res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  res.sendFile(path.join(DIST, 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Cortex client serving on :${PORT} (pre-compressed static)`);
});
