// Static file server for the Cortex client build.
// Serves pre-compressed .gz / .br files generated by vite-plugin-compression,
// with correct cache headers (long for hashed assets, no-cache for HTML).
import express from 'express';
import expressStaticGzip from 'express-static-gzip';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';
import { buildMetadata, injectMetadata, buildNoscript, injectNoscript } from './page-metadata.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.join(__dirname, 'dist');
const PORT = process.env.PORT || 3000;
// Bind host. Defaults to all interfaces (0.0.0.0) so a reverse proxy on
// another host can reach it (dev/QA). Set HOST=127.0.0.1 where nginx runs on
// the same box (e.g. the prod VPS, via its pm2 ecosystem env).
const HOST = process.env.HOST || '0.0.0.0';

// Where to ask about this instance. Same box by default; the static server and
// the API are separate processes but always deployed together.
const API_ORIGIN = process.env.API_ORIGIN || `http://127.0.0.1:${process.env.API_PORT || 3001}`;

const app = express();

// The shell, read once. It is immutable for the life of the process — a deploy
// replaces the file and restarts pm2.
let SHELL = null;
const shell = () => (SHELL ??= fs.readFileSync(path.join(DIST, 'index.html'), 'utf8'));

// Instance branding, cached. A link preview must not wait on an API call, and
// the instance name changes about once ever.
let brandingCache = { value: {}, at: 0 };
const BRANDING_TTL_MS = 5 * 60 * 1000;

async function branding() {
  if (Date.now() - brandingCache.at < BRANDING_TTL_MS) return brandingCache.value;
  try {
    const res = await fetch(`${API_ORIGIN}/api/instance-config`, { signal: AbortSignal.timeout(2000) });
    if (res.ok) {
      const cfg = await res.json();
      brandingCache = { value: cfg.branding || {}, at: Date.now() };
    }
  } catch {
    // Unreachable API: keep whatever we had and try again after the TTL. The
    // page still works; its metadata is just less specific.
    brandingCache.at = Date.now();
  }
  return brandingCache.value;
}

// The public lists, cached briefly. Short TTL because an event can be edited,
// and these exist to make a shared link unfurl and to give a scriptless reader
// something true.
//
// `null` means "could not find out", which is deliberately different from `[]`
// meaning "there are none". Only one of those is safe to render as an empty
// list.
const listCache = new Map();
const LIST_TTL_MS = 60 * 1000;

async function publicList(kind) {
  const hit = listCache.get(kind);
  if (hit && Date.now() - hit.at < LIST_TTL_MS) return hit.value;
  let value = null;
  try {
    const res = await fetch(`${API_ORIGIN}/api/public/${kind}`, { signal: AbortSignal.timeout(2000) });
    if (res.ok) {
      const data = await res.json();
      value = kind === 'events' ? (data.events || []) : (data.waves || []);
    }
  } catch { /* leave it null — see above */ }
  listCache.set(kind, { value, at: Date.now() });
  return value;
}

app.use(
  expressStaticGzip(DIST, {
    enableBrotli: true,
    orderPreference: ['br', 'gz'],
    // No directory-index lookup, and this MUST be top-level: express-static-gzip
    // reads `options.index`, never `options.serveStatic.index`. Placed inside
    // serveStatic in v2.105.6 it was inert, and the trailing-slash fix shipped
    // there was carried entirely by the `req.originalUrl` change below.
    //
    // Why it matters: with the lookup on, a request for `/events/` is rewritten
    // to `/events/index.html`, and `/` is answered by the static middleware
    // instead of the fallback — so `/` never reached the metadata composer and
    // kept the built-in title.
    //
    // Nothing is lost. `/` resolves through the fallback, which serves the same
    // file with the same no-cache headers, and now with its metadata composed.
    index: false,
    serveStatic: {
      etag: true,
      lastModified: true,
      setHeaders(res, filePath) {
        if (/\.html(?:\.gz|\.br)?$/.test(filePath) || /(?:^|\/)(sw\.js|manifest\.json)(?:\.gz|\.br)?$/.test(filePath)) {
          // HTML must never be cached — it references hashed asset filenames.
          // sw.js/manifest.json likewise: an immutable-cached service worker
          // can stay stale for up to 24h after a deploy (v2.60.3).
          res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
        } else {
          // Hashed assets (JS, CSS) are immutable — cache for 1 year
          res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
        }
      },
    },
  })
);

/**
 * robots.txt, composed rather than shipped as a file.
 *
 * There was none at all — a 404 — so crawlers had no guidance and no signal
 * about which of these pages are meant to be public. Almost all of Cortex is
 * private, and the two pages that are not (`/portal`, `/events`) are public
 * because an operator deliberately published them.
 *
 * It is generated because the answer depends on the instance: a node with the
 * public portal switched off has nothing to allow, and saying otherwise would
 * invite crawlers to pages that will only redirect them.
 */
app.get('/robots.txt', async (req, res) => {
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=3600');

  let portalPublic = true;
  try {
    const r = await fetch(`${API_ORIGIN}/api/instance-config`, { signal: AbortSignal.timeout(2000) });
    if (r.ok) portalPublic = ((await r.json()).features || {}).publicPortal !== false;
  } catch {
    // Unreachable API. Assume the portal is on, because the cost of being wrong
    // that way is a crawler following a link that redirects — whereas assuming
    // it is off would hide pages an operator chose to publish.
  }

  // ONE record, no blank lines inside it. A blank line terminates a record
  // (RFC 9309), so the first version of this file put every Disallow into an
  // orphaned group with no User-agent — malformed, and a parser that cannot read
  // robots.txt may decline to fetch at all.
  const lines = [
    '# Cortex. Almost everything here is private.',
    'User-agent: *',
    ...(portalPublic
      ? ['Allow: /portal', 'Allow: /events']
      : ['Disallow: /']),
    'Disallow: /api/',
    'Disallow: /uploads/',
    'Disallow: /waves',
    'Disallow: /settings',
    'Disallow: /admin',
    'Disallow: /cross-port/',
  ];
  // Comments go after the record, where a blank line is harmless.
  lines.push(
    '',
    '# The public pages render with JavaScript. Machine-readable equivalents,',
    '# no authentication required:',
    '#   /api/public/events                  JSON, every published event',
    '#   /api/public/events/calendar.ics     iCalendar, subscribable',
    '#   /api/public/portal                  JSON, the published pages',
  );
  res.send(`${lines.join('\n')}\n`);
});

// SPA fallback: unmatched ROUTES serve index.html (Express 5 wildcard syntax).
// File-like paths (last segment has an extension) must 404 instead: answering
// a missing /assets/*.js with 200 index.html lets the service worker cache
// HTML as if it were the bundle, permanently bricking clients whose shell
// still references a previous build's hashed assets (v2.60.3).
app.get('/{*path}', (req, res) => {
  // Judge the URL the CLIENT asked for, not `req.path`, which upstream
  // middleware is free to rewrite — that rewrite is exactly what broke
  // trailing-slash routes. `originalUrl` is set once and never altered.
  const requested = (req.originalUrl || req.path).split('?')[0].split('#')[0];
  const lastSegment = requested.split('/').pop() || '';
  if (lastSegment.includes('.')) {
    return res.status(404).type('text/plain').send('Not found');
  }
  res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  serveShell(req, res).catch(() => {
    // Metadata is a nicety; serving the page is not. Any failure falls back to
    // the file as built.
    res.send(shell());
  });
});

/**
 * The shell, with its <head> metadata composed for this URL.
 *
 * Not server-side rendering: the body is the same empty div and the page still
 * needs JavaScript to show anything. This fixes only what machines read —
 * link previews, crawlers, agents without a script runtime — which until now
 * saw "CORTEX - Secure Wave Communications" on every page of every instance.
 */
async function serveShell(req, res) {
  const proto = req.headers['x-forwarded-proto'] || req.protocol || 'https';
  const host = req.headers['x-forwarded-host'] || req.headers.host || '';
  const origin = host ? `${proto}://${host}` : '';
  const pathname = req.originalUrl || req.path;
  const brand = await branding();

  let meta = buildMetadata({ pathname, branding: brand, event: null, origin });

  // Private routes get metadata and nothing else: their content is not ours to
  // put in a page anyone can fetch.
  if (meta.route.kind === 'app') {
    return res.send(injectMetadata(shell(), meta));
  }

  const events = meta.route.kind === 'events' ? await publicList('events') : null;
  const portalWaves = meta.route.kind === 'portal' ? await publicList('portal') : null;

  if (meta.route.eventId && events) {
    const event = events.find(e => e.id === meta.route.eventId);
    if (event) meta = buildMetadata({ pathname, branding: brand, event, origin });
  }

  const noscript = buildNoscript({ route: meta.route, branding: brand, events, portalWaves });
  res.send(injectNoscript(injectMetadata(shell(), meta), noscript));
}

app.listen(PORT, HOST, () => {
  console.log(`Cortex client serving on ${HOST}:${PORT} (pre-compressed static)`);
});
