// Static file server for the Cortex client build.
// Serves pre-compressed .gz / .br files generated by vite-plugin-compression,
// with correct cache headers (long for hashed assets, no-cache for HTML).
import express from 'express';
import expressStaticGzip from 'express-static-gzip';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.join(__dirname, 'dist');
const PORT = process.env.PORT || 3000;
// Bind host. Defaults to all interfaces (0.0.0.0) so a reverse proxy on
// another host can reach it (dev/QA). Set HOST=127.0.0.1 where nginx runs on
// the same box (e.g. the prod VPS, via its pm2 ecosystem env).
const HOST = process.env.HOST || '0.0.0.0';

const app = express();

app.use(
  expressStaticGzip(DIST, {
    enableBrotli: true,
    orderPreference: ['br', 'gz'],
    serveStatic: {
      etag: true,
      lastModified: true,
      // No directory-index lookup. Without this, a request for `/events/`
      // becomes a search for `dist/events/index.html`, and serve-static
      // REWRITES req.path to `/events/index.html` before handing on — so the
      // SPA fallback below saw a filename with a dot in it and 404'd a
      // perfectly good route. `/events/` and `/portal/` both returned
      // "Not found" while `/events` worked, and the client router accepts
      // either (see AppContent.jsx, the pattern ends `\/?$`).
      //
      // Nothing is lost: `/` still resolves, via the fallback, which serves the
      // same file with the same no-cache headers. There is now exactly one
      // place that decides "this is a route, serve the shell".
      index: false,
      setHeaders(res, filePath) {
        if (/\.html(?:\.gz|\.br)?$/.test(filePath) || /(?:^|\/)(sw\.js|manifest\.json)(?:\.gz|\.br)?$/.test(filePath)) {
          // HTML must never be cached — it references hashed asset filenames.
          // sw.js/manifest.json likewise: an immutable-cached service worker
          // can stay stale for up to 24h after a deploy (v2.60.3).
          res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
        } else {
          // Hashed assets (JS, CSS) are immutable — cache for 1 year
          res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
        }
      },
    },
  })
);

// SPA fallback: unmatched ROUTES serve index.html (Express 5 wildcard syntax).
// File-like paths (last segment has an extension) must 404 instead: answering
// a missing /assets/*.js with 200 index.html lets the service worker cache
// HTML as if it were the bundle, permanently bricking clients whose shell
// still references a previous build's hashed assets (v2.60.3).
app.get('/{*path}', (req, res) => {
  // Judge the URL the CLIENT asked for, not `req.path`, which upstream
  // middleware is free to rewrite — that rewrite is exactly what broke
  // trailing-slash routes. `originalUrl` is set once and never altered.
  const requested = (req.originalUrl || req.path).split('?')[0].split('#')[0];
  const lastSegment = requested.split('/').pop() || '';
  if (lastSegment.includes('.')) {
    return res.status(404).type('text/plain').send('Not found');
  }
  res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  res.sendFile(path.join(DIST, 'index.html'));
});

app.listen(PORT, HOST, () => {
  console.log(`Cortex client serving on ${HOST}:${PORT} (pre-compressed static)`);
});
