// Each entry: [primaryName, ...aliases, unicodeChar]
// Last element is always the emoji character; all preceding strings are searchable names.
const EMOJI_DATA = [
  // ── Smileys & Emotion ──────────────────────────────────────────────────────
  ['grinning', '😀'], ['smile', '😄'], ['grin', '😁'], ['beaming', '😁'],
  ['joy', 'tears_of_joy', '😂'], ['rofl', 'rolling_on_floor', '🤣'],
  ['lol', 'laughing', '😆'], ['sweat_smile', '😅'], ['upside_down', '🙃'],
  ['wink', '😉'], ['blush', 'relieved_smile', '😊'], ['innocent', '😇'],
  ['heart_eyes', '😍'], ['kissing_heart', '😘'], ['kissing', '😗'],
  ['kissing_closed_eyes', '😚'], ['kissing_smiling_eyes', '😙'],
  ['yum', 'tongue', '😋'], ['stuck_out_tongue', '😛'],
  ['stuck_out_tongue_winking', '😜'], ['zany', 'crazy', '🤪'],
  ['stuck_out_tongue_closed', '😝'], ['money_mouth', '🤑'],
  ['hugging', 'hug', '🤗'], ['thinking', '🤔'], ['zipper_mouth', '🤐'],
  ['raised_eyebrow', '🤨'], ['neutral', '😐'], ['expressionless', '😑'],
  ['no_mouth', '😶'], ['smirk', '😏'], ['unamused', '😒'],
  ['roll_eyes', 'rolling_eyes', '🙄'], ['grimacing', '😬'],
  ['lying', 'pinocchio', '🤥'], ['shushing', 'quiet', '🤫'],
  ['thinking_face', '🤔'], ['hand_over_mouth', '🤭'],
  ['monocle', 'detective', '🧐'], ['nerd', '🤓'], ['sunglasses', '😎'],
  ['star_struck', 'starstruck', '🤩'], ['partying', '🥳'],
  ['melting', '🫠'], ['saluting', '🫡'], ['dotted_line_face', '🫥'],
  ['peeking', '🫣'], ['please', 'pleading', '🥺'],
  ['hot_face', 'hot', '🥵'], ['cold_face', 'cold', '🥶'],
  ['woozy', 'dizzy_swirl', '🥴'], ['exploding_head', 'mind_blown', '🤯'],
  ['astonished', '😲'], ['flushed', '😳'], ['anguished', '😧'],
  ['fearful', '😨'], ['cold_sweat', '😰'], ['anxious', 'sweat', '😥'],
  ['sad_relieved', '😓'], ['confused', '😕'], ['worried', '😟'],
  ['slightly_frowning', '🙁'], ['frowning', '☹️'], ['open_mouth', '😮'],
  ['hushed', '😯'], ['astonished2', '😲'], ['scream', '😱'],
  ['persevere', '😣'], ['disappointed', '😞'], ['sweat2', '😓'],
  ['weary', '😩'], ['tired', '😫'], ['yawning', '🥱'],
  ['triumph', '😤'], ['rage', 'angry_red', '😡'], ['angry', '😠'],
  ['skull_crossbones', '☠️'], ['skull', '💀'],
  ['cry', '😢'], ['sob', '😭'],
  ['sleeping', 'zzz_face', '😴'], ['sleepy', '😪'],
  ['dizzy_face', '😵'], ['dead', 'x_eyes', '😵'],
  ['nauseated', 'sick', '🤢'], ['sneezing', '🤧'], ['hot', '🥵'],
  ['mask', 'sick_mask', '😷'], ['thermometer_face', '🤒'],
  ['bandage_face', '🤕'], ['vomiting', '🤮'],
  ['lying_face', '🤥'], ['shrug', 'shrugging', '🤷'],
  ['facepalm', 'face_palm', '🤦'], ['no_good', '🙅'],
  ['ok_person', '🙆'], ['tipping_hand', 'information_desk', '💁'],
  ['raising_hand', '🙋'], ['bow', 'bowing', '🙇'],
  ['pout', 'pouting', '🙎'], ['person_frowning', '🙍'],
  ['ghost', '👻'], ['alien', '👽'], ['space_invader', '👾'],
  ['robot', '🤖'], ['poop', 'poo', 'shit', '💩'],
  ['clown', '🤡'], ['devil', 'smiling_imp', '😈'],
  ['imp', 'angry_devil', '👿'], ['japanese_ogre', '👹'],
  ['japanese_goblin', '👺'], ['skull2', '💀'], ['zzz', '💤'],

  // ── People & Body ──────────────────────────────────────────────────────────
  ['wave', 'waving', '👋'], ['raised_back_hand', '🤚'],
  ['raised_hand', 'stop', '✋'], ['vulcan', 'spock', '🖖'],
  ['ok_hand', 'ok', '👌'], ['pinched_fingers', '🤌'],
  ['pinching', '🤏'], ['fingers_crossed', 'lucky', '🤞'],
  ['love_you', '🤟'], ['metal', 'rock_on', '🤘'],
  ['call_me', 'hang_loose', '🤙'], ['point_left', '👈'],
  ['point_right', '👉'], ['point_up_2', '👆'], ['middle_finger', '🖕'],
  ['point_down', '👇'], ['point_up', '☝️'], ['thumbsup', '+1', 'like', '👍'],
  ['thumbsdown', '-1', 'dislike', '👎'], ['fist', 'fist_bump', '✊'],
  ['oncoming_fist', 'punch', '👊'], ['left_fist', '🤛'],
  ['right_fist', '🤜'], ['clap', 'clapping', '👏'],
  ['raised_hands', 'hooray', '🙌'], ['open_hands', '👐'],
  ['palms_up', '🤲'], ['pray', 'thanks', 'please', '🙏'],
  ['handshake', '🤝'], ['nail_care', '💅'], ['ear', '👂'],
  ['nose', '👃'], ['eyes', '👀'], ['eye', '👁️'],
  ['tongue', '👅'], ['lips', '👄'], ['brain', '🧠'],
  ['anatomical_heart', '🫀'], ['lungs', '🫁'], ['tooth', '🦷'],
  ['bone', '🦴'], ['leg', '🦵'], ['foot', '🦶'], ['muscle', 'flex', '💪'],
  ['writing_hand', 'writing', '✍️'], ['selfie', '🤳'],
  ['mechanical_arm', '🦾'], ['mechanical_leg', '🦿'],
  ['baby', '👶'], ['child', '🧒'], ['boy', '👦'], ['girl', '👧'],
  ['person', '🧑'], ['man', '👨'], ['woman', '👩'],
  ['older_adult', '🧓'], ['old_man', '👴'], ['old_woman', '👵'],

  // ── Hearts & Love ─────────────────────────────────────────────────────────
  ['heart', 'red_heart', '❤️'], ['orange_heart', '🧡'],
  ['yellow_heart', '💛'], ['green_heart', '💚'], ['blue_heart', '💙'],
  ['light_blue_heart', '🩵'], ['purple_heart', '💜'],
  ['brown_heart', '🤎'], ['black_heart', '🖤'], ['grey_heart', '🩶'],
  ['white_heart', '🤍'], ['pink_heart', '🩷'],
  ['broken_heart', 'heartbreak', '💔'], ['heart_fire', '❤️‍🔥'],
  ['heart_bandage', '❤️‍🩹'], ['sparkling_heart', '💖'],
  ['heartpulse', '💗'], ['beating_heart', '💓'],
  ['revolving_hearts', '💞'], ['two_hearts', '💕'],
  ['heart_decoration', '💟'], ['heavy_heart_exclamation', '❣️'],
  ['cupid', 'heart_arrow', '💘'], ['gift_heart', '💝'],
  ['heart_eyes_cat', '😻'], ['kissing_cat', '😽'],

  // ── Animals & Nature ──────────────────────────────────────────────────────
  ['dog', 'puppy', '🐶'], ['cat', 'kitty', '🐱'], ['mouse', '🐭'],
  ['hamster', '🐹'], ['rabbit', 'bunny', '🐰'], ['fox', '🦊'],
  ['bear', '🐻'], ['panda', '🐼'], ['koala', '🐨'],
  ['tiger', '🐯'], ['lion', '🦁'], ['cow', '🐮'], ['pig', '🐷'],
  ['pig_nose', '🐽'], ['frog', '🐸'], ['monkey', '🐵'],
  ['see_no_evil', '🙈'], ['hear_no_evil', '🙉'], ['speak_no_evil', '🙊'],
  ['monkey_face', '🐒'], ['chicken', '🐔'], ['penguin', '🐧'],
  ['bird', '🐦'], ['baby_chick', '🐤'], ['hatching_chick', '🐣'],
  ['hatched_chick', '🐥'], ['duck', '🦆'], ['eagle', '🦅'],
  ['owl', '🦉'], ['bat', '🦇'], ['wolf', '🐺'], ['boar', '🐗'],
  ['horse', '🐴'], ['unicorn', '🦄'], ['bee', 'honeybee', '🐝'],
  ['bug', '🐛'], ['butterfly', '🦋'], ['snail', '🐌'],
  ['shell', '🐚'], ['beetle', '🪲'], ['ant', '🐜'],
  ['mosquito', '🦟'], ['cricket', '🦗'], ['cockroach', '🪳'],
  ['spider', '🕷️'], ['scorpion', '🦂'], ['turtle', '🐢'],
  ['snake', '🐍'], ['dragon', '🐲'], ['dragon_face', '🐉'],
  ['sauropod', 'dinosaur', '🦕'], ['t_rex', 'trex', '🦖'],
  ['whale', '🐳'], ['whale2', '🐋'], ['dolphin', '🐬'],
  ['seal', '🦭'], ['fish', '🐟'], ['tropical_fish', '🐠'],
  ['blowfish', '🐡'], ['shark', '🦈'], ['octopus', '🐙'],
  ['crab', '🦀'], ['lobster', '🦞'], ['shrimp', '🦐'],
  ['squid', '🦑'], ['oyster', '🦪'], ['sneezing_cat', '🤧'],
  ['bouquet', '💐'], ['cherry_blossom', '🌸'], ['white_flower', '💮'],
  ['rosette', '🏵️'], ['rose', '🌹'], ['wilted_flower', '🥀'],
  ['hibiscus', '🌺'], ['sunflower', '🌻'], ['blossom', '🌼'],
  ['tulip', '🌷'], ['seedling', '🌱'], ['evergreen', '🌲'],
  ['deciduous', '🌳'], ['palm_tree', '🌴'], ['cactus', '🌵'],
  ['ear_of_rice', '🌾'], ['herb', '🌿'], ['shamrock', '☘️'],
  ['four_leaf_clover', '🍀'], ['maple_leaf', '🍁'],
  ['fallen_leaf', '🍂'], ['leaves', '🍃'], ['mushroom', '🍄'],
  ['chestnut', '🌰'], ['coral', '🪸'], ['feather', '🪶'],

  // ── Food & Drink ──────────────────────────────────────────────────────────
  ['grapes', '🍇'], ['melon', '🍈'], ['watermelon', '🍉'],
  ['tangerine', 'orange_fruit', '🍊'], ['lemon', '🍋'], ['banana', '🍌'],
  ['pineapple', '🍍'], ['mango', '🥭'], ['apple', '🍎'],
  ['green_apple', '🍏'], ['pear', '🍐'], ['peach', '🍑'],
  ['cherries', '🍒'], ['strawberry', '🍓'], ['blueberries', '🫐'],
  ['kiwi', '🥝'], ['tomato', '🍅'], ['olive', '🫒'],
  ['coconut', '🥥'], ['avocado', '🥑'], ['eggplant', 'aubergine', '🍆'],
  ['potato', '🥔'], ['carrot', '🥕'], ['corn', '🌽'],
  ['hot_pepper', '🌶️'], ['bell_pepper', '🫑'], ['cucumber', '🥒'],
  ['leafy_green', '🥬'], ['broccoli', '🥦'], ['garlic', '🧄'],
  ['onion', '🧅'], ['peanuts', '🥜'], ['beans', '🫘'],
  ['chestnut2', '🌰'], ['bread', '🍞'], ['croissant', '🥐'],
  ['baguette', '🥖'], ['flatbread', '🫓'], ['pretzel', '🥨'],
  ['bagel', '🥯'], ['pancakes', '🥞'], ['waffle', '🧇'],
  ['cheese', '🧀'], ['meat_on_bone', '🍖'], ['poultry_leg', '🍗'],
  ['cut_of_meat', 'steak', '🥩'], ['bacon', '🥓'], ['hamburger', 'burger', '🍔'],
  ['fries', '🍟'], ['pizza', '🍕'], ['hotdog', '🌭'],
  ['sandwich', '🥪'], ['taco', '🌮'], ['burrito', '🌯'],
  ['tamale', '🫔'], ['stuffed_flatbread', '🥙'], ['falafel', '🧆'],
  ['egg', '🥚'], ['fried_egg', '🍳'], ['shallow_pan', '🥘'],
  ['pot_of_food', '🍲'], ['fondue', '🫕'], ['bowl_with_spoon', '🥣'],
  ['green_salad', 'salad', '🥗'], ['popcorn', '🍿'], ['butter', '🧈'],
  ['salt', '🧂'], ['canned_food', '🥫'], ['bento', '🍱'],
  ['rice_cracker', '🍘'], ['rice_ball', '🍙'], ['rice', '🍚'],
  ['curry', '🍛'], ['ramen', '🍜'], ['spaghetti', '🍝'],
  ['sweet_potato', '🍠'], ['oden', '🍢'], ['sushi', '🍣'],
  ['fried_shrimp', '🍤'], ['fish_cake', '🍥'], ['moon_cake', '🥮'],
  ['dango', '🍡'], ['dumpling', '🥟'], ['fortune_cookie', '🥠'],
  ['takeout_box', '🥡'], ['crab2', '🦀'], ['soft_ice_cream', '🍦'],
  ['shaved_ice', '🍧'], ['ice_cream', '🍨'], ['doughnut', 'donut', '🍩'],
  ['cookie', '🍪'], ['birthday', 'cake', '🎂'], ['shortcake', '🍰'],
  ['cupcake', '🧁'], ['pie', '🥧'], ['chocolate_bar', 'chocolate', '🍫'],
  ['candy', '🍬'], ['lollipop', '🍭'], ['custard', '🍮'],
  ['honey_pot', 'honey', '🍯'], ['baby_bottle', '🍼'],
  ['glass_of_milk', 'milk', '🥛'], ['coffee', 'hot_beverage', '☕'],
  ['teapot', '🫖'], ['tea', '🍵'], ['sake', '🍶'],
  ['champagne', 'bottle_with_popping_cork', '🍾'],
  ['wine', 'wine_glass', '🍷'], ['cocktail', '🍸'],
  ['tropical_drink', '🍹'], ['beer', '🍺'], ['beers', 'cheers', '🍻'],
  ['clinking_glasses', '🥂'], ['tumbler_glass', 'whiskey', '🥃'],
  ['pouring', '🫗'], ['cup_with_straw', '🥤'], ['bubble_tea', 'boba', '🧋'],
  ['beverage_box', '🧃'], ['mate', '🧉'], ['ice_cube', '🧊'],
  ['chopsticks', '🥢'], ['fork_knife_plate', '🍽️'],
  ['fork_and_knife', '🍴'], ['spoon', '🥄'],

  // ── Activities & Sports ───────────────────────────────────────────────────
  ['soccer', 'football', '⚽'], ['basketball', '🏀'], ['football2', 'american_football', '🏈'],
  ['baseball', '⚾'], ['softball', '🥎'], ['tennis', '🎾'],
  ['volleyball', '🏐'], ['rugby', '🏉'], ['flying_disc', 'frisbee', '🥏'],
  ['8ball', 'billiards', '🎱'], ['ping_pong', 'table_tennis', '🏓'],
  ['badminton', '🏸'], ['hockey', '🏒'], ['field_hockey', '🏑'],
  ['lacrosse', '🥍'], ['cricket_game', '🏏'], ['boomerang', '🪃'],
  ['goal_net', '🥅'], ['golf', '⛳'], ['fishing', '🎣'],
  ['diving', '🤿'], ['boxing_glove', '🥊'], ['martial_arts', '🥋'],
  ['ice_skate', '⛸️'], ['ski', '🎿'], ['sled', '🛷'],
  ['curling_stone', '🥌'], ['dart', '🎯'], ['skateboard', '🛹'],
  ['trophy', '🏆'], ['medal', '🥇'], ['second_place', '🥈'],
  ['third_place', '🥉'], ['sports_medal', '🏅'], ['ribbon', '🎀'],
  ['ticket', '🎫'], ['circus', '🎪'], ['performing_arts', '🎭'],
  ['art', 'palette', '🎨'], ['slot_machine', '🎰'],
  ['game_die', 'dice', '🎲'], ['chess', '♟️'], ['jigsaw', 'puzzle', '🧩'],
  ['teddy_bear', '🧸'], ['pinata', '🪅'], ['nesting_dolls', '🪆'],
  ['spades', '♠️'], ['hearts', '♥️'], ['diamonds', '♦️'], ['clubs', '♣️'],
  ['joker', '🃏'], ['mahjong', '🀄'], ['flower_playing_cards', '🎴'],

  // ── Travel & Places ───────────────────────────────────────────────────────
  ['car', 'automobile', '🚗'], ['taxi', '🚕'], ['bus', '🚌'],
  ['trolleybus', '🚎'], ['racing_car', '🏎️'], ['police_car', '🚓'],
  ['ambulance', '🚑'], ['fire_truck', '🚒'], ['minibus', '🚐'],
  ['truck', '🚚'], ['articulated_lorry', '🚛'], ['tractor', '🚜'],
  ['kick_scooter', '🛴'], ['bicycle', 'bike', '🚲'],
  ['motor_scooter', '🛵'], ['motorcycle', '🏍️'],
  ['monorail', '🚝'], ['mountain_railway', '🚞'], ['train', '🚋'],
  ['train2', '🚆'], ['bullet_train', '🚅'], ['railway_car', '🚃'],
  ['airplane', 'plane', '✈️'], ['small_airplane', '🛩️'],
  ['rocket', '🚀'], ['flying_saucer', 'ufo', '🛸'],
  ['seat', '💺'], ['helicopter', '🚁'], ['suspension_railway', '🚟'],
  ['boat', 'sailboat', '⛵'], ['canoe', '🛶'],
  ['speedboat', '🚤'], ['ship', '🚢'], ['ferry', '⛴️'],
  ['anchor', '⚓'], ['ring_buoy', '🛟'],
  ['construction', '🚧'], ['fuel_pump', '⛽'], ['traffic_light', '🚦'],
  ['globe', 'earth_africa', '🌍'], ['earth_americas', '🌎'],
  ['earth_asia', '🌏'], ['world_map', '🗺️'], ['japan', '🗾'],
  ['compass', '🧭'], ['mountain', '⛰️'], ['mount_fuji', '🗻'],
  ['camping', '🏕️'], ['beach', '🏖️'], ['desert', '🏜️'],
  ['desert_island', '🏝️'], ['stadium', '🏟️'],
  ['classical_building', '🏛️'], ['building_construction', '🏗️'],
  ['houses', '🏘️'], ['house', '🏠'], ['house_with_garden', '🏡'],
  ['office', '🏢'], ['post_office', '🏣'], ['hospital', '🏥'],
  ['bank', '🏦'], ['hotel', '🏨'], ['school', '🏫'],
  ['love_hotel', '🏩'], ['wedding', '💒'], ['castle', '🏯'],
  ['european_castle', '🏰'], ['statue_of_liberty', '🗽'],
  ['moyai', 'moai', '🗿'], ['sunrise', '🌅'], ['city_sunrise', '🌇'],
  ['night_with_stars', '🌃'], ['cityscape', '🏙️'],
  ['sunset', '🌆'], ['bridge_at_night', '🌉'],
  ['milky_way', '🌌'], ['stars', '🌠'], ['sparkler', '🎇'],
  ['fireworks', '🎆'],

  // ── Objects ───────────────────────────────────────────────────────────────
  ['glasses', '👓'], ['sunglasses2', '🕶️'], ['goggles', '🥽'],
  ['lab_coat', '🥼'], ['safety_vest', '🦺'], ['necktie', '👔'],
  ['shirt', '👕'], ['jeans', '👖'], ['scarf', '🧣'], ['gloves', '🧤'],
  ['coat', '🧥'], ['socks', '🧦'], ['dress', '👗'], ['kimono', '👘'],
  ['sari', '🥻'], ['bikini', '👙'], ['womans_clothes', '👚'],
  ['purse', '👛'], ['handbag', '👜'], ['clutch_bag', '👝'],
  ['shopping', '🛍️'], ['backpack', '🎒'], ['luggage', '🧳'],
  ['mans_shoe', '👞'], ['boot', '👢'], ['flat_shoe', '🥿'],
  ['sandal', '👡'], ['high_heel', '👠'], ['sneaker', '👟'],
  ['safety_pin', '🧷'], ['sewing', '🪡'], ['thread', '🧵'],
  ['yarn', '🧶'], ['lab_microscope', '🔬'], ['telescope', '🔭'],
  ['satellite', '📡'], ['syringe', '💉'], ['pill', '💊'],
  ['adhesive_bandage', 'bandaid', '🩹'], ['stethoscope', '🩺'],
  ['door', '🚪'], ['mirror', '🪞'], ['window', '🪟'],
  ['bed', '🛏️'], ['couch', '🛋️'], ['chair', '🪑'],
  ['toilet', '🚽'], ['plunger', '🪠'], ['shower', '🚿'],
  ['bathtub', '🛁'], ['razor', '🪒'], ['lotion', '🧴'],
  ['safety_pin2', '🧷'], ['broom', '🧹'], ['basket', '🧺'],
  ['roll_of_paper', 'toilet_paper', '🧻'], ['bucket', '🪣'],
  ['soap', '🧼'], ['toothbrush', '🪥'], ['sponge', '🧽'],
  ['fire_extinguisher', '🧯'], ['shopping_cart', '🛒'],
  ['smoking', '🚬'], ['coffin', '⚰️'], ['headstone', '🪦'],
  ['moyai2', '🗿'], ['atm', '🏧'], ['litter', '🚮'],
  ['potable_water', '🚰'], ['wheelchair', '♿'], ['mens', '🚹'],
  ['womens', '🚺'], ['restroom', '🚻'], ['baby_symbol', '🚼'],
  ['wc', '🚾'], ['passport_control', '🛂'], ['customs', '🛃'],
  ['baggage_claim', '🛄'], ['left_luggage', '🛅'],
  ['warning', '⚠️'], ['children_crossing', '🚸'],
  ['no_entry', '⛔'], ['no_entry_sign', '🚫'], ['no_bicycles', '🚳'],
  ['no_smoking', '🚭'], ['do_not_litter', '🚯'],
  ['non_potable_water', '🚱'], ['no_pedestrians', '🚷'],
  ['no_mobile_phones', '📵'], ['underage', '🔞'],
  ['radioactive', '☢️'], ['biohazard', '☣️'],
  ['arrow_up', '⬆️'], ['arrow_down', '⬇️'],
  ['arrow_left', '⬅️'], ['arrow_right', '➡️'],
  ['recycle', '♻️'], ['fleur_de_lis', '⚜️'],
  ['beginner', '🔰'], ['heavy_check', '✔️'],
  ['check', '✅'], ['x', 'cross', '❌'], ['negative_squared_cross', '❎'],
  ['plus', '➕'], ['minus', '➖'], ['divide', '➗'], ['multiply', '✖️'],
  ['curly_loop', '➰'], ['loop', '➿'],
  ['question', '❓'], ['grey_question', '❔'],
  ['grey_exclamation', '❕'], ['exclamation', '❗'],
  ['100', 'hundred', '💯'], ['1234', '🔢'],
  ['information', 'ℹ️'], ['hash', '#️⃣'],

  // ── Symbols & Signs ───────────────────────────────────────────────────────
  ['heart_suit', '♥️'], ['diamond_suit', '♦️'],
  ['spade_suit', '♠️'], ['club_suit', '♣️'],
  ['aries', '♈'], ['taurus', '♉'], ['gemini', '♊'], ['cancer', '♋'],
  ['leo', '♌'], ['virgo', '♍'], ['libra', '♎'], ['scorpius', '♏'],
  ['sagittarius', '♐'], ['capricorn', '♑'], ['aquarius', '♒'], ['pisces', '♓'],
  ['om', '🕉️'], ['star_of_david', '✡️'], ['wheel_of_dharma', '☸️'],
  ['yin_yang', '☯️'], ['cross', '✝️'], ['orthodox_cross', '☦️'],
  ['peace', 'peace_symbol', '☮️'], ['menorah', '🕎'],
  ['six_pointed_star', '🔯'],

  // ── Nature / Weather ──────────────────────────────────────────────────────
  ['sunny', 'sun', '☀️'], ['cloud', '☁️'], ['partly_cloudy', '⛅'],
  ['cloud_rain', 'rainy', '🌧️'], ['thunder_cloud', 'thunderstorm', '⛈️'],
  ['lightning', 'zap', '⚡'], ['snowflake', '❄️'], ['snowman', '⛄'],
  ['snowman2', '☃️'], ['comet', '☄️'], ['fire', '🔥'],
  ['droplet', 'drop', '💧'], ['ocean', 'wave', '🌊'],
  ['rainbow', '🌈'], ['fog', '🌫️'], ['tornado', '🌪️'],
  ['cyclone', 'hurricane', '🌀'], ['sparkles', 'stars2', '✨'],
  ['star', '⭐'], ['star2', 'glowing_star', '🌟'], ['dizzy', '💫'],
  ['boom', 'collision', '💥'], ['night', 'crescent_moon', '🌙'],
  ['full_moon', '🌕'], ['new_moon', '🌑'], ['sun_with_face', '🌞'],
  ['moon_face', '🌝'], ['earth', 'globe2', '🌍'],
  ['volcano', '🌋'], ['milky_way2', '🌌'], ['sunrise2', '🌄'],

  // ── Office & Tech ─────────────────────────────────────────────────────────
  ['phone', 'telephone', '☎️'], ['mobile', 'iphone', '📱'],
  ['calling', '📲'], ['laptop', 'computer', '💻'], ['desktop', '🖥️'],
  ['printer', '🖨️'], ['keyboard', '⌨️'], ['mouse2', '🖱️'],
  ['trackball', '🖲️'], ['minidisc', '💽'], ['floppy_disk', '💾'],
  ['cd', '💿'], ['dvd', '📀'], ['abacus', '🧮'],
  ['movie_camera', '🎥'], ['film_frames', '🎞️'], ['telephone_receiver', '📞'],
  ['pager', '📟'], ['fax', '📠'], ['battery', '🔋'], ['electric_plug', '🔌'],
  ['bulb', 'lightbulb', '💡'], ['flashlight', '🔦'], ['candle', '🕯️'],
  ['money_with_wings', '💸'], ['dollar', '💵'], ['euro', '💶'],
  ['pound', '💷'], ['yen', '💴'], ['moneybag', 'money', '💰'],
  ['gem', 'diamond', '💎'], ['credit_card', '💳'],
  ['chart_increasing', '📈'], ['chart_decreasing', '📉'],
  ['bar_chart', '📊'], ['clipboard', '📋'], ['notepad', '📓'],
  ['notebook', '📔'], ['books', '📚'], ['book', 'open_book', '📖'],
  ['ledger', '📒'], ['memo', 'pencil', '📝'], ['calendar', '📅'],
  ['spiral_calendar', '🗓️'], ['card_index', '📇'], ['file_cabinet', '🗄️'],
  ['wastebasket', 'trash', '🗑️'], ['inbox', '📥'], ['outbox', '📤'],
  ['package', '📦'], ['email', 'envelope', '📧'], ['inbox2', '📨'],
  ['envelope_arrow', '📩'], ['envelope_pen', '📩'],
  ['outbox_tray', '📤'], ['label', '🏷️'], ['bookmark', '🔖'],
  ['moneybag2', '💰'], ['chart', '📊'],
  ['magnifying_glass', 'search', '🔍'], ['magnifying_glass_right', '🔎'],
  ['lock', '🔒'], ['unlock', '🔓'], ['key', '🔑'], ['old_key', '🗝️'],
  ['hammer', '🔨'], ['axe', '🪓'], ['pick', '⛏️'], ['hammer_pick', '⚒️'],
  ['tools', '🛠️'], ['dagger', '🗡️'], ['sword', '⚔️'], ['shield', '🛡️'],
  ['wrench', '🔧'], ['screwdriver', '🪛'], ['nut_and_bolt', '🔩'],
  ['gear', 'settings', '⚙️'], ['chains', '⛓️'], ['hook', '🪝'],
  ['toolbox', '🧰'], ['magnet', '🧲'], ['ladder', '🪜'],
  ['microscope', '🔬'], ['telescope2', '🔭'], ['satellite2', '📡'],
  ['syringe2', '💉'], ['pill2', '💊'],
  ['bell', '🔔'], ['no_bell', '🔕'], ['tada', 'party', '🎉'],
  ['confetti', '🎊'], ['balloon', '🎈'], ['flags', '🎏'],
  ['ribbon2', '🎀'], ['gift', 'present', '🎁'],
  ['reminder_ribbon', '🎗️'], ['ticket2', '🎟️'], ['microphone', '🎤'],
  ['headphones', '🎧'], ['radio', '📻'], ['saxophone', '🎷'],
  ['guitar', '🎸'], ['piano', '🎹'], ['trumpet', '🎺'],
  ['violin', '🎻'], ['banjo', '🪕'], ['drum', '🥁'], ['long_drum', '🪘'],
  ['microphone2', '🎙️'], ['notes', 'music', '🎶'], ['note', '🎵'],
  ['studio_microphone', '🎙️'], ['level_slider', '🎚️'],
  ['control_knobs', '🎛️'],
  ['iphone2', '📱'], ['phone2', '☎️'], ['tv', '📺'],
  ['camera', '📷'], ['camera_flash', '📸'], ['video_camera', '📹'],
  ['movie_projector', '📽️'], ['film_projector', '🎦'],
  ['compass2', '🧭'], ['world_map2', '🗺️'],
  ['pin', 'pushpin', '📌'], ['paperclip', '📎'],
  ['link', '🔗'], ['scissors', '✂️'], ['pen', '🖊️'],
  ['paintbrush', '🖌️'], ['crayon', '🖍️'],
  ['rocket2', '🚀'], ['flying_saucer2', '🛸'],

  // ── Misc fun ──────────────────────────────────────────────────────────────
  ['thumbsup2', '👍'], ['thumbsdown2', '👎'],
  ['red_envelope', '🧧'], ['lantern', '🏮'],
  ['mirror_ball', 'disco', '🪩'], ['carousel', '🎠'],
  ['ferris_wheel', '🎡'], ['roller_coaster', '🎢'],
  ['art2', '🎨'], ['circus2', '🎪'],
  ['moyai3', '🗿'], ['nazar', '🧿'],
  ['piñata', '🪅'], ['nesting_dolls2', '🪆'],
  ['thread2', '🧵'], ['yarn2', '🧶'],
  ['crystal_ball', 'fortune', '🔮'], ['magic_wand', '🪄'],
  ['joystick', '🕹️'], ['game_die2', '🎲'],
  ['chess_pawn', '♟️'], ['jigsaw2', '🧩'],
  ['puzzle', '🧩'], ['teddy', '🧸'],
];

export const EMOJI_MAP = new Map();
export const EMOJI_LIST = [];

for (const entry of EMOJI_DATA) {
  const char = entry[entry.length - 1];
  const primaryName = entry[0];
  for (let i = 0; i < entry.length - 1; i++) {
    EMOJI_MAP.set(entry[i], char);
  }
  if (!EMOJI_LIST.find(e => e.char === char)) {
    EMOJI_LIST.push({ name: primaryName, char });
  }
}

export function searchEmoji(query) {
  if (!query) return EMOJI_LIST.slice(0, 20);
  const q = query.toLowerCase();
  // Exact prefix matches first, then contains
  const prefix = EMOJI_LIST.filter(e => e.name.startsWith(q));
  const contains = EMOJI_LIST.filter(e => !e.name.startsWith(q) && e.name.includes(q));
  return [...prefix, ...contains].slice(0, 20);
}

export function resolveEmojiShortcodes(text) {
  return text.replace(/:([a-z0-9_+\-]+):/gi, (match, code) => {
    return EMOJI_MAP.get(code.toLowerCase()) || match;
  });
}
